fix(Changes): fix comparison when `Source` is missing
Previously `__lt__` raised an exception:

```
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

Just use an empty string to avoid `None`. This is okay as the key is
only used for sorting.